services:
  redpanda:
    image: redpandadata/redpanda:latest
    command: >
      redpanda start --overprovisioned --smp 1 --memory 1G
      --reserve-memory 0M --node-id 0 --check=false
      --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr redpanda:9092,localhost:9092
    ports: ["9092:9092"]

  jobmanager:
    image: flink:1.17-scala_2.12-java11
    ports: ["8081:8081"]
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///opt/flink/checkpoints
        state.savepoints.dir: file:///opt/flink/savepoints
        rest.bind-port: 8081
    volumes:
      - flink-checkpoints:/opt/flink/checkpoints
      - flink-savepoints:/opt/flink/savepoints

  taskmanager:
    image: flink:1.17-scala_2.12-java11
    depends_on: [jobmanager]
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        state.backend: filesystem
        state.checkpoints.dir: file:///opt/flink/checkpoints
        state.savepoints.dir: file:///opt/flink/savepoints
    volumes:
      - flink-checkpoints:/opt/flink/checkpoints
      - flink-savepoints:/opt/flink/savepoints

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      - KAFKA_BROKER=redpanda:9092
    depends_on: [redpanda]
    restart: unless-stopped

  flink-job:
    build:
      context: .
      dockerfile: Dockerfile.flink
    environment:
      - KAFKA_BROKER=redpanda:9092
      - FLINK_JOBMANAGER_HOST=jobmanager
      - FLINK_JOBMANAGER_PORT=8081
    depends_on: [redpanda, jobmanager, taskmanager]
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports: ["8503:8501"]
    environment:
      - KAFKA_BROKER=redpanda:9092
    depends_on: [redpanda]
    restart: unless-stopped

volumes:
  flink-checkpoints:
  flink-savepoints:
